export default {
    GET_CONTACT_LIST: 'GET_CONTACT_LIST',
    GET_USERNAME: 'GET_USERNAME',
    LOGIN: 'LOGIN',
    UPDATE_SHOW_LOGIN_FORM: 'UPDATE_SHOW_LOGIN_FORM',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    GET_PRODUCTS_INFO: 'GET_PRODUCTS_INFO',
}
